version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: vote-app-backend:dev
    command: npx nodemon --watch . --exec "node server.js"
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "4000:4000"
    environment:
      - MONGODB_URI=mongodb://mongo:27017/vote-app
      - JWT_SECRET=${JWT_SECRET}
      - NODE_ENV=development
    depends_on:
      - mongo

  mongo:
    image: mongo:6
    volumes:
      - mongo_dev_data:/data/db
    ports:
      - "27017:27017"

volumes:
  mongo_dev_data:
